AWSTemplateFormatVersion: '2010-09-09'
Resources:
  FastAPIECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: fastapi-cluster

  FastAPITaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ecs-tasks.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "AmazonECSTaskExecutionRolePolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:BatchGetImage"
                  - "ecr:GetAuthorizationToken"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                  - "s3:GetObject"
                Resource: "*"

  FastAPITaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: fastapi-task
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ExecutionRoleArn: !GetAtt FastAPITaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: fastapi-container
          Image: your-account-id.dkr.ecr.your-region.amazonaws.com/fastapi-chat:latest
          PortMappings:
            - ContainerPort: 80
              HostPort: 80

  FastAPIFargateService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref FastAPIECSCluster
      TaskDefinition: !Ref FastAPITaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - subnet-0XXX  # Replace with your subnet ID
          SecurityGroups:
            - sg-XXXX # Replace with your security group ID
